services:
  mc:
    container_name: neoforge-1.21.1-thriller
    image: itzg/minecraft-server
    environment:
      TYPE: MODRINTH
      VERSION: "1.21.1"
      EULA: true

      INIT_MEMORY: 6G
      MEMORY: 12G
      USE_AIKAR_FLAGS: true

      PVP: true
      ALLOW_FLIGHT: true
      ENABLE_COMMAND_BLOCK: true
      DIFFICULTY: "hard"
      MOTD: "Cauchemar"

      LEVEL_TYPE: FLAT
      GENERATE_STRUCTURES: false
      GENERATOR_SETTINGS: >-
        {
            "layers": [
                {
                    "block": "minecraft:bedrock",
                    "height": 1
                },
                {
                    "block": "minecraft:stone",
                    "height": 350
                }
            ],
            "biome": "minecraft:plains"
        }

      MODRINTH_MODPACK: "/server.mrpack"
    networks:
      - proxy
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    volumes:
      - ./data:/data
      - ./server.mrpack:/server.mrpack
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  proxy:
    external: true
    name: proxy-network
